# example_config.toml
# Contains every possible default option

[global]
# The modules that are enabled and will be displayed
modules = ["directory", "git", "prompt"]
# Color of the text
foreground = "bright_white"
# Color of the background
background = "blue"
# Font style
style = "default"
# Goes after each module
separator = ""
# Padding before the text of each module
padding_left = " "
# Padding after the text of each module
padding_right = " "

[modules.directory]
# How many directory levels to show before truncating
max_depth = 4

# Displays the exit code of the last-executed command
[modules.exit_code]
# Background to show on success
bg_success = "green"
# Background to show on failure
bg_error = "red"

[modules.git]
# Symbol to represent an insertion
symbol_insertion = "+"
# Symbol to represent a deletion
symbol_deletion = "-"
# Symbol to represent unpushed commits to upstream
symbol_push = "⇡"
# Symbol to represent unpulled commits from upstream
symbol_push = "⇣"
# Whether or not to show a symbol if repository has been modified
show_changed = true
# Whether or not to show the number of insertions/deletions
show_diff_stats = false
# Whether or not to show unpushed/unpulled commits to/from upstream
show_unpushed = true

[modules.prompt]
# What to display
output = "$"
# Background to show on success
bg_success = "green"
# Background to show on failure
bg_error = "red"
